# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "lab" do |a|
    a.vm.provider "docker" do |d|

      d.build_dir = "."
      d.ports = ["80:80","3306:3306"]
      d.name = "local"
      d.has_ssh = true
    end
    a.vm.hostname = "local.local"

    a.vm.synced_folder "../../../../", "/home/vagrant/barbarians"

    a.ssh.port = 22
    a.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../playbook.yml"
      ansible.inventory_path = "inventory"
      ansible.verbose = 'vvvv'
      #ansible.start_at_task = "Check if Drupal is booting."
    end
  end

  # config.vm.define "precoinfo_solr" do |a|
  #   a.vm.provider "docker" do |d|
  #
  #     d.build_dir = "."
  #     d.ports = ["2223:22"]
  #     d.name = "precoinfo_solr"
  #     d.has_ssh = true
  #   end
  #   a.vm.hostname = "precoinfo.solr"
  #
  #   #a.vm.synced_folder "../../../../", "/home/vagrant/precoinfo-webapp"
  #   #a.vm.synced_folder "../../../../../precoinfo-api/", "/home/vagrant/precoinfo-api"
  #
  #   a.ssh.port = 22
  #   a.vm.provision "ansible" do |ansible|
  #     ansible.playbook = "../../playbook.yml"
  #     ansible.inventory_path = "inventory"
  #     ansible.verbose = 'vvvv'
  #     #ansible.start_at_task = "Check if Drupal is booting."
  #   end
  # end
end
